# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vbguest.auto_update = false if Vagrant.has_plugin?('vagrant-vbguest')
    config.vm.define :servidor do |servidor|
    servidor.vm.box = "bento/ubuntu-22.04"
    servidor.vm.network "private_network", ip: "192.168.50.3"
    servidor.vm.hostname = "servidor"
    servidor.vm.synced_folder "compartir", "/compartir"

    end
    config.vm.define :cliente do |cliente|
    cliente.vm.box = "bento/ubuntu-22.04"
    cliente.vm.network "private_network", ip: "192.168.50.2"
    cliente.vm.hostname = "cliente"
    cliente.vm.synced_folder "compartir", "/compartir"

    end
end